import Head from 'next/head'
import Image from 'next/image'
import Valorant from '../components/valorant/Valorant'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Valorant/>
    </div>
  )
}
